package com.ccihackathon.comrade.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table REMINDER.
 */
public class Reminder extends ReminderBase  {
    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    public Reminder() {
    }

    public Reminder(Long id) {
        super(id);
    }

    public Reminder(Long id, String reminder, String location, String latitude, String longitude, String notify) {
        super(id, reminder, location, latitude, longitude, notify);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
