package com.ccihackathon.comrade.db;






// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table REMINDER.
 */
abstract public class ReminderBase {

    protected Long id;
    protected String guid;
    protected String reminder;
    protected String location;
    protected String latitude;
    protected String longitude;
    protected String notify;




    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ReminderBase() {
    }

    public ReminderBase(Long id) {
        this.id = id;
    }

    public ReminderBase(Long id, String guid, String reminder, String location, String latitude, String longitude, String notify) {
        this.id = id;
        this.guid = guid;
        this.reminder = reminder;
        this.location = location;
        this.latitude = latitude;
        this.longitude = longitude;
        this.notify = notify;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGuid() {
        return guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getReminder() {
        return reminder;
    }

    public void setReminder(String reminder) {
        this.reminder = reminder;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getNotify() {
        return notify;
    }

    public void setNotify(String notify) {
        this.notify = notify;
    }

    public void updateNotNull(Reminder other) {
        if(other.id != null) {
            this.id = other.id;
        }

        if(other.guid != null) {
            this.guid = other.guid;
        }

        if(other.reminder != null) {
            this.reminder = other.reminder;
        }

        if(other.location != null) {
            this.location = other.location;
        }

        if(other.latitude != null) {
            this.latitude = other.latitude;
        }

        if(other.longitude != null) {
            this.longitude = other.longitude;
        }

        if(other.notify != null) {
            this.notify = other.notify;
        }

        // relationships
    }


    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public void onBeforeSave() {
        //you can override this method and do some stuff if you want to :)

    }
}
